import { ArrowRight, CheckCircle2, FilePenLine, Plus, Send } from 'lucide-react'
import { Link, useNavigate } from 'react-router-dom'
import { calculateReadiness } from '../../domain/readiness'
import { ReadinessBadge, SegmentedProgress } from '../../components/ui/Readiness'
import { useAppStore } from '../../store/useAppStore'

export function BusinessDashboard(){
  const {tasks,proposals,createTask}=useAppStore();const navigate=useNavigate();const own=tasks.filter(t=>t.draft.organization.includes('Точка ремонта')||t.draft.organization==='Моя демонстрационная компания');const published=own.filter(t=>t.published).length;const newP=proposals.filter(p=>own.some(t=>t.id===p.taskId)&&p.status==='Отправлен').length;const chosen=proposals.filter(p=>own.some(t=>t.id===p.taskId)&&p.status==='Выбрана').length;const improve=[...own].sort((a,b)=>calculateReadiness(a.draft).score-calculateReadiness(b.draft).score)[0]
  const create=()=>{const id=createTask();navigate(`/tasks/${id}/edit`)}
  return <div className="page"><div className="page-heading"><div><span className="eyebrow">Кабинет бизнеса</span><h1>Мастерская задач</h1><p>Подготовьте понятную задачу и найдите студенческую команду</p></div><button className="btn" onClick={create}><Plus size={19}/>Создать задачу</button></div>
    <section className="stats" aria-label="Показатели"><div><Send/><span><strong>{published}</strong>Опубликованные задачи</span></div><div><FilePenLine/><span><strong>{newP}</strong>Новые отклики</span></div><div><CheckCircle2/><span><strong>{chosen}</strong>Выбранные команды</span></div></section>
    {improve&&<section className="spotlight"><div><span className="eyebrow">Ближайшее полезное действие</span><h2>{improve.draft.title}</h2><p>{calculateReadiness(improve.draft).score<40?'Заполните ожидаемый результат и критерии приёмки — командам станет проще понять границы проекта.':'Проверьте неподтверждённые сведения и подготовьте новую опубликованную версию.'}</p><Link className="btn secondary" to={`/tasks/${improve.id}/edit`}>Дополнить описание<ArrowRight size={17}/></Link></div><div className="spot-score"><span className="huge-number">{calculateReadiness(improve.draft).score}</span><span>из 100</span><SegmentedProgress value={calculateReadiness(improve.draft).score}/></div></section>}
    <section><div className="section-head"><div><span className="eyebrow">Рабочий список</span><h2>Мои задачи</h2></div><span className="muted">{own.length} задач</span></div><div className="task-list">{own.map(task=>{const r=calculateReadiness(task.draft);return <div className="task-row" key={task.id}><div className="task-main"><span className={`status-dot ${task.published?'published':'draft'}`}/><div><Link to={`/tasks/${task.id}`}>{task.draft.title||'Новая задача без названия'}</Link><small>{task.published?'Опубликована':'Приватный черновик'} · обновлено {new Intl.DateTimeFormat('ru-RU',{day:'numeric',month:'short',timeZone:'Asia/Almaty'}).format(new Date(task.updatedAt))}</small></div></div><ReadinessBadge draft={task.draft} compact/><span className="responses">{task.applications} откл.</span><Link className="btn ghost small" to={`/tasks/${task.id}/edit`}>{r.score<70?'Дополнить':'Открыть'}<ArrowRight size={16}/></Link></div>})}</div></section>
  </div>
}
