import { useEffect, useRef, useState } from 'react'
import { ArrowLeft, ArrowRight, Check, CheckCircle2, CircleAlert, LoaderCircle, Sparkles } from 'lucide-react'
import { Link, useNavigate, useParams } from 'react-router-dom'
import { calculateReadiness, readinessCriteria } from '../../domain/readiness'
import type { AiAnalysis } from '../../services/mockAiService'
import { analyzeDraft } from '../../services/mockAiService'
import { SegmentedProgress } from '../../components/ui/Readiness'
import { useAppStore } from '../../store/useAppStore'

const stages=['Проблема','Уточнения','Карточка','Проверка']
const labels={title:'Название задачи',industry:'Сфера бизнеса',organization:'Организация',problem:'Опишите проблему своими словами',context:'Контекст',need:'Потребность бизнеса',users:'Кто будет пользоваться результатом',data:'Данные и материалы',constraints:'Ограничения',outcome:'Ожидаемый результат',successCriteria:'Критерии успеха',contact:'Контакт',interactionFormat:'Формат взаимодействия',feedbackProcess:'Порядок обратной связи'} as const
const demo={title:'Единый учёт заявок мастерской',industry:'Ремонт и услуги',problem:'У нас небольшая мастерская. Заявки приходят в сообщениях и записываются в разные таблицы. Хочу видеть все заказы и их статусы.',context:'Заявки поступают через мессенджеры и по телефону, а затем вручную переносятся в разные таблицы.',need:'Собрать заказы в одном месте и видеть актуальный статус каждого.',skills:['Исследование','Проектирование данных','Прототипирование']}

export function TaskEditor({createOnMount=false}:{createOnMount?:boolean}){
  const params=useParams();const navigate=useNavigate();const made=useRef(false);const {tasks,createTask,updateTaskField,confirmCriterion,publishTask,setNotice}=useAppStore();const [stage,setStage]=useState(0);const [analysis,setAnalysis]=useState<AiAnalysis>();const [aiState,setAiState]=useState<'idle'|'loading'|'error'>('idle');
  useEffect(()=>{if(createOnMount&&!made.current){made.current=true;const id=createTask();navigate(`/tasks/${id}/edit`,{replace:true})}},[createOnMount,createTask,navigate])
  const task=tasks.find(t=>t.id===params.id);if(createOnMount&&!params.id)return <div className="page center-state"><LoaderCircle className="spin"/><p>Создаём черновик…</p></div>;if(!task)return <div className="page center-state"><CircleAlert/><h1>Задача не найдена</h1><Link className="btn" to="/business">Вернуться в кабинет</Link></div>
  const r=calculateReadiness(task.draft);const change=(field:keyof typeof labels,value:string)=>updateTaskField(task.id,field,value);const runAi=async()=>{setAiState('loading');try{setAnalysis(await analyzeDraft(task.draft));setAiState('idle')}catch{setAiState('error')}}
  const useDemo=()=>{Object.entries(demo).forEach(([key,value])=>updateTaskField(task.id,key as keyof typeof demo,value));setNotice('Демопример явно добавлен в черновик','info')}
  const publish=()=>{if(publishTask(task.id)){setNotice('Новая версия задачи опубликована');navigate(`/tasks/${task.id}`)}else setNotice('Добавьте название и описание проблемы','danger')}
  const field=(name:keyof typeof labels,area=true,placeholder='')=><label className="field" htmlFor={name}><span>{labels[name]}</span>{area?<textarea id={name} rows={name==='problem'?6:3} value={String(task.draft[name])} onChange={e=>change(name,e.target.value)} placeholder={placeholder}/>:<input id={name} value={String(task.draft[name])} onChange={e=>change(name,e.target.value)} placeholder={placeholder}/>}</label>
  return <div className="editor-page"><div className="editor-head"><Link to="/business" className="back-link"><ArrowLeft size={17}/>Мастерская задач</Link><div><span className="eyebrow">Конструктор задачи</span><h1>{task.draft.title||'Новая задача'}</h1><p>{task.published?'Редактируется новая версия. Опубликованная карточка не изменится до подтверждения.':'Приватный черновик · сохраняется автоматически'}</p></div></div>
    <div className="stepper" aria-label="Этапы конструктора">{stages.map((name,i)=><button key={name} className={stage===i?'active':stage>i?'done':''} onClick={()=>setStage(i)}><span>{stage>i?<Check size={15}/>:i+1}</span>{name}</button>)}</div>
    <div className="editor-grid"><section className="editor-work">
      {stage===0&&<><div className="stage-intro"><span>01</span><div><h2>Опишите реальную проблему</h2><p>Начните со своей ситуации. Решение можно сформулировать позже вместе с командой.</p></div></div><button className="demo-fill" onClick={useDemo}><Sparkles size={18}/><span><strong>Использовать демопример мастерской</strong><small>Поля будут заполнены явно — вы сможете всё изменить</small></span></button>{field('title',false,'Например, Единый учёт заказов')}{field('industry',false,'Ремонт, услуги, образование…')}{field('organization',false)}{field('problem',true,'Что происходит сейчас и почему это мешает работе?')}<div className="form-actions"><span/><button className="btn" onClick={()=>{setStage(1);void runAi()}}>Получить уточнения<ArrowRight size={17}/></button></div></>}
      {stage===1&&<><div className="stage-intro"><span>02</span><div><h2>Уточните важные детали</h2><p>Вопросы зависят от введённых сведений. Ответ записывается в конкретное поле карточки.</p></div></div><div className="ai-label"><Sparkles size={16}/>Демо-анализ — без подключения AI</div>{aiState==='loading'?<div className="loading-panel"><LoaderCircle className="spin"/><span>Подбираем вопросы по описанию…</span></div>:aiState==='error'?<div className="error-panel"><p>Не удалось подготовить вопросы. Черновик сохранён.</p><button className="btn secondary" onClick={runAi}>Повторить</button></div>:analysis?.questions.length?<div className="questions">{analysis.questions.map((q,i)=><label className="question" key={q.field}><span><i>{String(i+1).padStart(2,'0')}</i>{q.text}</span><textarea rows={3} value={String(task.draft[q.field])} onChange={e=>updateTaskField(task.id,q.field,e.target.value)}/></label>)}</div>:<div className="success-panel"><CheckCircle2/><div><strong>Основные сведения уже заполнены</strong><p>Перейдите к карточке, чтобы проверить формулировки.</p></div></div>}<div className="form-actions"><button className="btn ghost" onClick={()=>setStage(0)}>Назад</button><button className="btn" onClick={()=>setStage(2)}>Продолжить вручную<ArrowRight size={17}/></button></div></>}
      {stage===2&&<><div className="stage-intro"><span>03</span><div><h2>Соберите карточку задачи</h2><p>Проверьте структурированный результат. Неизвестные сведения оставлены пустыми.</p></div></div><div className="form-grid">{field('context')}{field('need')}{field('users')}{field('data')}{field('constraints')}{field('outcome')}{field('successCriteria')}{field('contact',false,'name@company.example.invalid')}{field('interactionFormat',false,'Например, встреча раз в неделю')}{field('feedbackProcess',false,'Когда и как вы даёте комментарии')}</div><div className="form-actions"><button className="btn ghost" onClick={()=>setStage(1)}>Назад</button><button className="btn" onClick={()=>setStage(3)}>Перейти к проверке<ArrowRight size={17}/></button></div></>}
      {stage===3&&<><div className="stage-intro"><span>04</span><div><h2>Подтвердите сведения</h2><p>Баллы начисляются только за заполненные и подтверждённые вами группы полей.</p></div></div><div className="confirmation-list">{readinessCriteria.map(item=>{const row=r.items.find(x=>x.key===item.key)!;return <label key={item.key} className={`confirm-row ${row.complete?'':'disabled'}`}><input type="checkbox" checked={row.confirmed} disabled={!row.complete} onChange={e=>confirmCriterion(task.id,item.key,e.target.checked)}/><span><strong>{item.label}</strong><small>{row.complete?'Я проверил(а) сведения, они верны':'Сначала заполните необходимые поля'}</small></span><b>+{item.weight}</b></label>})}</div><div className="publish-note"><CircleAlert/><p>Публикация видна всем демонстрационным командам. Рейтинг показывает полноту подтверждённых сведений, а не качество будущего решения.</p></div><div className="form-actions"><button className="btn ghost" onClick={()=>setStage(2)}>Назад</button><button className="btn" onClick={publish}>Подтвердить и опубликовать</button></div></>}
    </section><aside className="readiness-panel"><div className="score-orbit"><span className="score-value">{r.score}</span><span>из 100</span></div><h2>{r.level}</h2><p>Предварительный рейтинг редактируемой версии</p><SegmentedProgress value={r.score}/><div className="criteria">{r.items.map(item=><button key={item.key} onClick={()=>{setStage(2);setTimeout(()=>document.getElementById(item.fieldId)?.focus(),50)}}><span className={item.earned?'earned':''}>{item.earned?<Check size={13}/>:null}</span><span>{item.label}<small>{item.complete&&!item.confirmed?'Заполнено, нужно подтвердить':item.earned?'Подтверждено':`Уточните: доступно до +${item.weight}`}</small></span><b>{item.earned}/{item.weight}</b></button>)}</div><div className="formula-note">Чистая бинарная шкала: критерий даёт полный вес только когда все связанные поля заполнены и подтверждены.</div></aside></div>
  </div>
}
