import { ArrowLeft, ArrowRight, BookOpen, CheckCircle2, ExternalLink, Send, Users } from 'lucide-react'
import { FormEvent, useState } from 'react'
import { Link, useParams } from 'react-router-dom'
import { ReadinessBadge, SegmentedProgress } from '../../components/ui/Readiness'
import { Modal } from '../../components/ui/Modal'
import { useAppStore } from '../../store/useAppStore'
import { calculateReadiness } from '../../domain/readiness'

export function TaskDetails(){const {id}=useParams();const {tasks,role,currentTeamId,proposals,addProposal,setNotice}=useAppStore();const [open,setOpen]=useState(false);const [sending,setSending]=useState(false);const task=tasks.find(t=>t.id===id);if(!task)return <div className="page center-state"><h1>Задача не найдена</h1><Link className="btn" to="/catalog">В каталог</Link></div>;const d=task.publishedSnapshot||task.draft;const existing=proposals.find(p=>p.taskId===task.id&&p.teamId===currentTeamId)
  const submit=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();if(sending)return;setSending(true);const fd=new FormData(e.currentTarget);const ok=addProposal({taskId:task.id,teamId:currentTeamId,idea:String(fd.get('idea')),plan:String(fd.get('plan')),duration:String(fd.get('duration')),prototypeUrl:String(fd.get('url')||'')||undefined});if(ok){setNotice('Отклик сохранён и виден бизнесу');setOpen(false)}else setNotice('Ваша команда уже откликнулась на эту задачу','info');setSending(false)}
  return <div className="page task-detail"><Link className="back-link" to="/catalog"><ArrowLeft size={17}/>Каталог задач</Link><header className="detail-hero"><div><div className="title-meta"><span>{d.industry}</span><span>Демонстрационная организация</span></div><h1>{d.title}</h1><p className="lead">{d.problem}</p><div className="org-line"><span className="org-avatar">{d.organization.slice(0,1)}</span><span><strong>{d.organization}</strong><small>Контакт: {d.contact||'уточняется после выбора команды'}</small></span></div></div><div className="detail-action"><ReadinessBadge draft={d}/><SegmentedProgress value={calculateReadiness(d).score}/>{role==='student'?(existing?<div className="submitted"><CheckCircle2/><span><strong>Отклик сохранён</strong><small>Статус: {existing.status}</small></span></div>:<button className="btn full" onClick={()=>setOpen(true)}><Send size={18}/>Откликнуться</button>):role==='business'?<><Link className="btn full" to={`/business/tasks/${task.id}/proposals`}><Users size={18}/>Смотреть предложения</Link><Link className="btn secondary full" to={`/tasks/${task.id}/edit`}>Редактировать</Link></>:<Link className="btn full" to="/projects/project-workshop"><BookOpen size={18}/>Открыть учебный план</Link>}</div></header>
    <div className="detail-columns"><section><span className="eyebrow">Практический результат</span><h2>Результат для бизнеса</h2><dl className="detail-list"><div><dt>Потребность</dt><dd>{d.need||'Уточняется'}</dd></div><div><dt>Данные и материалы</dt><dd>{d.data||'Пока не указаны'}</dd></div><div><dt>Ограничения</dt><dd>{d.constraints||'Пока не указаны'}</dd></div><div><dt>Критерии приёмки</dt><dd>{d.successCriteria||'Нужно согласовать с бизнесом'}</dd></div></dl></section><section className="learning-section"><span className="eyebrow violet">Учебный маршрут</span><h2>Чему научится команда</h2><div className="skill-tags large">{d.skills.map(s=><span key={s}>{s}</span>)}</div><ol className="mini-roadmap">{['Разобраться в проблеме','Спроектировать данные','Собрать прототип','Проверить решение','Защитить личный вклад'].map((x,i)=><li key={x}><span>{i+1}</span>{x}</li>)}</ol><div className="plan-status">Предложенный план · требует подтверждения наставника</div></section></div>
    {open&&<Modal title="Отклик команды" onClose={()=>setOpen(false)}><form className="modal-form" onSubmit={submit}><p>Опишите подход команды. После отправки бизнес увидит отклик в сравнении предложений.</p><label>Идея решения<textarea required name="idea" rows={4} placeholder="С чего начнёте и на чём сфокусируетесь?"/></label><label>План работы<textarea required name="plan" rows={3} placeholder="Например: интервью → схема → прототип → проверка"/></label><label>Предполагаемый срок<input required name="duration" placeholder="Например, 4 недели"/></label><label>Ссылка на прототип <small>необязательно</small><input name="url" type="url" placeholder="https://example.invalid/prototype"/></label><div className="modal-actions"><button type="button" className="btn ghost" onClick={()=>setOpen(false)}>Отмена</button><button className="btn" disabled={sending}>{sending?'Отправляем…':'Отправить отклик'}<ArrowRight size={17}/></button></div></form></Modal>}
  </div>}
