import {test,after} from 'node:test';
import assert from 'node:assert/strict';
import {createHash,randomUUID} from 'node:crypto';
import {db} from '../lib/db';
import {register,login,setCredentials,sessionUser,revokeSession,revokeAllSessions,checkOrigin,consumeRate,hashPassword,checkPassword} from '../lib/auth';
import {getData} from '../lib/data';
import {saveProfile} from '../lib/profile';
import {act} from '../lib/actions';
import {emptyFields} from '../lib/domain';

after(()=>db.$disconnect());
const password='A test phrase with spaces 42!';
const registration=(username:string,role='student')=>({name:'Test learner',role,username,password,confirmPassword:password});
test('origin checks allow only explicitly configured LAN addresses',()=>{
 const request=(origin?:string)=>new Request('http://127.0.0.1:3000/api/auth/login',{headers:origin?{origin}:{}});
 checkOrigin(request('http://127.0.0.1:3000'));
 assert.throws(()=>checkOrigin(request()));
 assert.throws(()=>checkOrigin(request('https://evil.example')));
 assert.throws(()=>checkOrigin(request('http://192.168.1.77:3000')));
 process.env.APP_ORIGINS='http://192.168.1.77:3000';
 checkOrigin(request('http://192.168.1.77:3000'));
 assert.throws(()=>checkOrigin(request('http://192.168.1.77:4000')));
 process.env.APP_ORIGINS='';
 process.env.APP_URL='http://127.0.0.1:3002';
 checkOrigin(request('http://localhost:3002'));assert.throws(()=>checkOrigin(request('http://localhost:3000')));
 process.env.APP_URL='http://127.0.0.1:3000';
});
test('passwords are salted, verified, and never stored as plaintext',async()=>{
 const first=await hashPassword(password),second=await hashPassword(password);
 assert.notEqual(first,second);assert(!first.includes(password));
 assert(await checkPassword(password,first));assert(!(await checkPassword('wrong password',first)));
 assert(!(await checkPassword(password,'broken hash')));
});
test('registration validates credentials and rejects duplicate normalized usernames atomically',async()=>{
 for(const invalid of [{username:'a'},{username:'bad login'},{password:'short',confirmPassword:'short'},{confirmPassword:'different'},{phone:'+15555550101'}])await assert.rejects(()=>register({...registration('validation'),...invalid}));
 const first=await register(registration(' Mixed_Name '));assert.equal(first.user.username,'mixed_name');
 const user=await sessionUser(first.token);assert(user);assert.equal(user.phone,null);assert(user.passwordHash);
 assert(!('passwordHash' in first.user));assert(!('phone' in first.user));
 const teamCount=await db.team.count();
 await assert.rejects(()=>register(registration('MIXED_NAME')),{status:409});
 assert.equal(await db.team.count(),teamCount);
 const wrong=await login({username:'mixed_name',password:'incorrect'}).catch(e=>e);
 const missing=await login({username:'unknown_account',password:'incorrect'}).catch(e=>e);
 assert.equal(wrong.status,401);assert.equal(missing.status,401);assert.equal(wrong.message,missing.message);
});
test('two devices share a saved profile while sessions can be revoked independently',async()=>{
 const first=await register(registration('two_devices'));
 const owner=await sessionUser(first.token);assert(owner);
 const publicBefore=await getData();assert(!publicBefore.profiles.some(p=>p.id===owner.id));assert(!publicBefore.teams.some(t=>t.id===owner.actorId));
 const profile={name:'Updated name',bio:'Learning through practice',location:'Алматы',education:'University',skills:['React'],website:'https://example.org',publicProfile:true,teamName:'Test Makers',memberCount:2};
 await saveProfile(owner,profile);
 const second=await login({username:'TWO_DEVICES',password});assert.notEqual(first.token,second.token);
 assert.equal(second.user.id,owner.id);assert.equal(second.user.name,profile.name);
 assert.equal(await db.user.count({where:{username:'two_devices'}}),1);
 const publicData=await getData();assert(publicData.profiles.some(p=>p.name===profile.name));
 assert(!JSON.stringify(publicData).includes('passwordHash'));assert(!JSON.stringify(publicData).includes(password));
 await assert.rejects(()=>saveProfile(owner,{...profile,website:'javascript:alert(1)'}));
 await saveProfile(owner,{...profile,publicProfile:false});assert(!(await getData()).profiles.some(p=>p.id===owner.id));
 await revokeSession(first.token);assert.equal(await sessionUser(first.token),null);assert(await sessionUser(second.token));
 await revokeAllSessions(owner.id);assert.equal(await sessionUser(second.token),null);
 assert.equal(await sessionUser('forged-token'),null);
});
test('expired sessions cannot authenticate and quotas persist in the database',async()=>{
 const session=await register(registration('expired_session'));
 await db.session.updateMany({where:{userId:session.user.id},data:{expiresAt:new Date(0)}});
 assert.equal(await sessionUser(session.token),null);
 await consumeRate('unit-quota',1,3600);await assert.rejects(()=>consumeRate('unit-quota',1,3600),{status:429});
});
test('legacy owners set credentials without losing work, revoking older sessions',async()=>{
 const actorId=randomUUID();await db.team.create({data:{id:actorId,name:'Legacy team',interests:'[]',skills:'[]',technologies:'[]',memberCount:1,bio:'',isDemo:false}});
 const legacy=await db.user.create({data:{phone:'+15555550999',provider:'mock',role:'student',name:'Legacy owner',bio:'Preserved biography',actorId}});
 const oldToken=randomUUID();await db.session.create({data:{tokenHash:createHash('sha256').update(oldToken).digest('hex'),userId:legacy.id,expiresAt:new Date(Date.now()+60000)}});
 const updated=await setCredentials(legacy,{username:'legacy_owner',password,confirmPassword:password});
 assert.equal(updated.user.id,legacy.id);assert.equal(updated.user.actorId,actorId);assert.equal(updated.user.bio,legacy.bio);
 assert.equal(await sessionUser(oldToken),null);assert(await sessionUser(updated.token));
 assert.equal((await login({username:'legacy_owner',password})).user.id,legacy.id);
 await assert.rejects(()=>setCredentials(legacy,{username:'hijack_owner',password,confirmPassword:password}),{status:409});
});
test('account ownership keeps drafts and proposals private',async()=>{
 const business=await register(registration('test_business','business')),team=await register(registration('test_student'));
 const owner=await sessionUser(business.token),student=await sessionUser(team.token);assert(owner&&student);
 const actor={role:owner.role,id:owner.actorId};
 const task=await act('createTask',{title:'Private auth test task',topic:'Образование',fields:{...emptyFields(),need:'Создать тестовую форму'},learning:{skills:[],prerequisites:[],portfolio:'Проект',difficulty:'Начальная'}},actor);assert('id'in task);
 assert(!(await getData()).tasks.some(t=>t.id===task.id));assert((await getData(owner)).tasks.some(t=>t.id===task.id));
 await assert.rejects(()=>act('confirmTask',{id:task.id},{role:student.role,id:student.actorId}));
 await act('confirmTask',{id:task.id},actor);await act('publishTask',{id:task.id},actor);
 const proposal=await act('createProposal',{taskId:task.id,idea:'Конфиденциальная идея команды',plan:['Проверить форму'],durationDays:7,prototypeUrl:'https://example.org'},{role:student.role,id:student.actorId});assert('id'in proposal);
 assert(!(await getData()).proposals.some(p=>p.id===proposal.id));assert((await getData(owner)).proposals.some(p=>p.id===proposal.id));assert((await getData(student)).proposals.some(p=>p.id===proposal.id));
 await assert.rejects(()=>act('resetDemo',{confirm:'RESET_DEMO'},actor));
});
