import {test} from 'node:test';
import assert from 'node:assert/strict';
import {calculateScore,emptyFields,fieldKeys,readinessLevel,retainConfirmations,safeUrl,validField,type Fields} from '../lib/domain';
import {mockAI,validateOutput,aiInput} from '../lib/ai';
import demo from '../data/demo-flow.json';
test('20 → 60 → 100 is based on confirmed fields',()=>{const fields:Fields={...emptyFields(),context:demo.suggestedAnswers.context,need:demo.suggestedAnswers.need};const confirmed=['context','need'];assert.equal(calculateScore(fields,confirmed),20);for(const stage of demo.stages){for(const field of stage.fields){fields[field as keyof Fields]=demo.suggestedAnswers[field as keyof Fields];confirmed.push(field)}assert.equal(calculateScore(fields,confirmed),stage.expectedScore)}assert.equal(calculateScore(fields,[]),0)});
test('level boundaries',()=>{for(const [score,level]of [[39,'draft'],[40,'working'],[69,'working'],[70,'ready'],[89,'ready'],[90,'priority']] as const)assert.equal(readinessLevel(score),level)});
test('placeholders and invalid contacts are not rewarded; editing clears confirmation',()=>{for(const value of ['',' ','-','не знаю','потом','не указано'])assert.equal(calculateScore({...emptyFields(),data:value},['data']),0);assert.equal(validField('contact','позвоните как-нибудь'),false);assert.equal(validField('contact','demo@example.org'),true);const before={...emptyFields(),context:'Есть исходные данные',need:'Построить учебный отчёт'};assert.deepEqual(retainConfirmations(before,{...before,context:'Новый контекст'},['context','need']),['need']);assert.equal(safeUrl('javascript:alert(1)'),false);assert.equal(safeUrl('//evil.example'),false)});
test('mock AI preserves unknowns, asks 3 questions, uses only supplied answers',()=>{const input=aiInput.parse({mode:'questions',draft:{id:'draft',text:'У нас кафе. Хотим улучшить закупки.',industry:'Кафе'},answers:[]});const questions=validateOutput('questions',mockAI(input),input);assert('questions'in questions&&questions.questions.length>=3);const cardInput={...input,mode:'card' as const};const result=validateOutput('card',mockAI(cardInput),cardInput);assert('card'in result);assert.equal(result.card.data,null);assert.equal(result.card.contact,null);const withAnswers={...cardInput,answers:[{id:'a1',questionId:'q-data',text:'Есть CSV продаж за 90 дней'}]};const filled=validateOutput('card',mockAI(withAnswers),withAnswers);assert('card'in filled);assert.equal(filled.card.data,'Есть CSV продаж за 90 дней');assert.throws(()=>validateOutput('questions',{},input));assert.throws(()=>validateOutput('card',{...filled,evidence:[{field:'title',sourceIds:['invented']}]},withAnswers));const full={...input,answers:fieldKeys.map(k=>({id:k,questionId:`q-${k}`,text:'Заполненное поле'}))};assert('questions' in validateOutput('questions',mockAI(full),full));});
