import {test,after} from 'node:test';
import assert from 'node:assert/strict';
import {db} from '../lib/db';
import {act} from '../lib/actions';
import {emptyFields} from '../lib/domain';
after(async()=>{await db.$disconnect()});
test('publication, low-score proposals, manual multiple selection, milestone and award idempotency',async()=>{
 const business={role:'business',id:'test-business'},student={role:'student',id:'test-team'},other={role:'student',id:'test-other'};
 await db.business.create({data:{id:business.id,name:'Учебный бизнес',industry:'Образование',contact:'test@example.org'}});
 for(const actor of [student,other])await db.team.create({data:{id:actor.id,name:actor.id,interests:'[]',skills:'[]',technologies:'[]',memberCount:3,bio:'Учебная команда'}});
 const payload={title:'Задача для проверки',topic:'Образование',fields:{...emptyFields(),context:'Есть процесс ручной обработки заявок',need:'Нужна понятная форма заявки'},learning:{skills:['Валидация'],prerequisites:['JavaScript'],portfolio:'Учебное приложение',difficulty:'Начальная'}};
 await assert.rejects(()=>act('createTask',payload,student));
 const created=await act('createTask',payload,business);assert('id'in created);const taskId=created.id;
 await assert.rejects(()=>act('publishTask',{id:taskId},business));
 await act('confirmTask',{id:taskId},business);await act('publishTask',{id:taskId},business);
 assert.equal((await db.task.findUniqueOrThrow({where:{id:taskId}})).readinessScore,20);
 const proposalPayload={taskId,idea:'Сделаем учебную форму с проверкой полей',plan:['Согласовать поля формы','Создать и проверить форму'],durationDays:7,prototypeUrl:'/demo/prototypes/sample'};
 const first=await act('createProposal',proposalPayload,student),second=await act('createProposal',proposalPayload,other);assert('id'in first&&'id'in second);
 await assert.rejects(()=>act('decideProposal',{id:first.id,status:'selected'},student));
 await act('decideProposal',{id:first.id,status:'selected'},business);await act('decideProposal',{id:second.id,status:'selected'},business);
 assert.equal(await db.proposal.count({where:{taskId,status:'selected'}}),2);
 await act('decideProposal',{id:first.id,status:'rejected'},business);await act('decideProposal',{id:second.id,status:'rejected'},business);assert.equal(await db.proposal.count({where:{taskId,status:'selected'}}),0);
 await act('decideProposal',{id:first.id,status:'selected'},business);
 const milestone=await db.milestone.findUniqueOrThrow({where:{proposalId:first.id}});
 await assert.rejects(()=>act('confirmMilestone',{id:milestone.id},business));
 await assert.rejects(()=>act('submitMilestone',{id:milestone.id,result:'Учебный результат готов',resultUrl:'/demo/prototypes/sample'},other));
 await act('submitMilestone',{id:milestone.id,result:'Сделана форма, проверены обязательные поля и отправка',resultUrl:'/demo/prototypes/sample'},student);
 await act('confirmMilestone',{id:milestone.id},business);await act('confirmMilestone',{id:milestone.id},business);
 assert.equal((await db.team.findUniqueOrThrow({where:{id:student.id}})).practicePoints,50);assert.equal(await db.award.count({where:{milestoneId:milestone.id}}),1);
 await act('updateTask',{id:taskId,task:{...payload,fields:{...payload.fields,context:'Изменённый контекст задачи'}}},business);
 assert.equal((await db.task.findUniqueOrThrow({where:{id:taskId}})).readinessScore,10);
 assert.equal(await db.proposal.count({where:{taskId}}),2);
});
