import { Search, SlidersHorizontal, X } from 'lucide-react'
import { useMemo, useState } from 'react'
import { Link } from 'react-router-dom'
import { calculateReadiness } from '../../domain/readiness'
import { ReadinessBadge } from '../../components/ui/Readiness'
import { useAppStore } from '../../store/useAppStore'

export function Catalog(){const {tasks,teams,currentTeamId}=useAppStore();const [query,setQuery]=useState('');const [topic,setTopic]=useState('Все темы');const [level,setLevel]=useState('Все уровни');const [sort,setSort]=useState('rating');const team=teams.find(t=>t.id===currentTeamId)!
  const topics=['Все темы',...new Set(tasks.filter(t=>t.published).map(t=>t.draft.industry).filter(Boolean))]
  const found=useMemo(()=>tasks.filter(t=>t.published).filter(t=>{const source=t.publishedSnapshot||t.draft;const r=calculateReadiness(source);return(!query||`${source.title} ${source.organization} ${source.problem}`.toLowerCase().includes(query.toLowerCase()))&&(topic==='Все темы'||source.industry===topic)&&(level==='Все уровни'||r.level===level)}).sort((a,b)=>sort==='rating'?calculateReadiness(b.publishedSnapshot||b.draft).score-calculateReadiness(a.publishedSnapshot||a.draft).score:a.draft.title.localeCompare(b.draft.title,'ru')),[tasks,query,topic,level,sort])
  const reset=()=>{setQuery('');setTopic('Все темы');setLevel('Все уровни')}
  return <div className="page"><div className="page-heading"><div><span className="eyebrow">Открытые проекты</span><h1>Каталог практических задач</h1><p>Все опубликованные задачи доступны командам — уровень готовности не ограничивает отклик</p></div></div><section className="filters"><label className="search"><Search size={18}/><span className="sr-only">Поиск задач</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Поиск по задаче или организации"/></label><label><span className="sr-only">Тема</span><select value={topic} onChange={e=>setTopic(e.target.value)}>{topics.map(x=><option key={x}>{x}</option>)}</select></label><label><span className="sr-only">Уровень готовности</span><select value={level} onChange={e=>setLevel(e.target.value)}>{['Все уровни','Черновик','Рабочая','Готовая','Приоритетная'].map(x=><option key={x}>{x}</option>)}</select></label><label><span className="sr-only">Сортировка</span><select value={sort} onChange={e=>setSort(e.target.value)}><option value="rating">Сначала готовые</option><option value="name">По названию</option></select></label></section><div className="results-head"><span>Найдено: <strong>{found.length}</strong></span>{(query||topic!=='Все темы'||level!=='Все уровни')&&<button className="text-btn" onClick={reset}><X size={15}/>Сбросить фильтры</button>}</div>
    {found.length?<div className="catalog-grid">{found.map(task=>{const d=task.publishedSnapshot||task.draft;const matches=d.skills.filter(s=>team.skills.includes(s)).length;return <article className={`task-card ${task.priority?'priority':''}`} key={task.id}>{task.priority&&<span className="priority-label">Приоритетная задача</span>}<div className="card-top"><span className="industry-icon"><SlidersHorizontal size={18}/></span><ReadinessBadge draft={d} compact/></div><h2><Link to={`/tasks/${task.id}`}>{d.title}</Link></h2><p className="org">{d.organization} · демонстрационная организация</p><p className="clamp">{d.problem}</p><div className="skill-tags">{d.skills.map(skill=><span key={skill}>{skill}</span>)}</div><div className="expected"><small>Ожидаемый результат</small><span>{d.outcome||'Уточняется вместе с командой'}</span></div><div className="card-footer"><span>{matches} из {d.skills.length} навыков совпадают</span><span>{task.applications} откликов</span></div></article>})}</div>:<div className="empty-state"><Search/><h2>Задачи не найдены</h2><p>Измените условия поиска или сбросьте фильтры.</p><button className="btn secondary" onClick={reset}>Сбросить фильтры</button></div>}
  </div>}
