import { Award, BookOpen, Check, CheckCircle2, Circle, CircleAlert, Clock3, Send, ShieldCheck } from 'lucide-react'
import { useState } from 'react'
import { Link, useParams } from 'react-router-dom'
import { useAppStore } from '../../store/useAppStore'

const statusIcon=(status:string)=>status==='Подтверждён'?<Check size={16}/>:status==='На проверке'?<Clock3 size={16}/>:status==='Нужна доработка'?<CircleAlert size={16}/>:<Circle size={14}/>
export function LearningProjectPage(){const {id}=useParams();const {projects,tasks,teams,role,updateMilestone,submitMilestone,reviewMilestone,confirmPlan,setNotice}=useAppStore();const project=projects.find(p=>p.id===id);const [selected,setSelected]=useState(0);const [comment,setComment]=useState('');if(!project)return <div className="page center-state"><h1>Учебный проект не найден</h1><Link className="btn" to="/student">К моей практике</Link></div>;const task=tasks.find(t=>t.id===project.taskId)!;const team=teams.find(t=>t.id===project.teamId)!;const m=project.milestones[selected];const confirmed=project.milestones.filter(x=>x.status==='Подтверждён').length
  const submit=()=>{if(!m.result.trim()){setNotice('Сначала добавьте результат работы','danger');return}submitMilestone(project.id,m.id);setNotice('Работа отправлена наставнику')};const review=(status:'Подтверждён'|'Нужна доработка')=>{reviewMilestone(project.id,m.id,status,comment);setNotice(status==='Подтверждён'?(m.xpAwarded?'Этап уже был подтверждён — повторные XP не начислены':'Этап подтверждён, команде начислено 100 XP'):'Этап возвращён на доработку');setComment('')}
  return <div className="page learning-page"><header className="learning-head"><div><span className="eyebrow violet">Учебное пространство</span><h1>{task.draft.title}</h1><p>{team.name} · {task.draft.organization}</p></div><div className="learning-progress"><strong>{confirmed}/{project.milestones.length}</strong><span>этапов подтверждено</span><div><i style={{width:`${confirmed/project.milestones.length*100}%`}}/></div></div></header><div className={`plan-banner ${project.planStatus==='Подтверждён наставником'?'confirmed':''}`}><ShieldCheck/><div><strong>{project.planStatus}</strong><p>{project.planStatus==='Подтверждён наставником'?'Наставник проверил последовательность учебных целей.':'Это предложенный шаблон, а не автоматически аккредитованная программа.'}</p></div>{role==='mentor'&&project.planStatus!=='Подтверждён наставником'&&<button className="btn secondary" onClick={()=>{confirmPlan(project.id);setNotice('Учебный план подтверждён наставником')}}>Подтвердить план</button>}</div>
    <div className="learning-layout"><nav className="milestone-map" aria-label="Карта учебных этапов">{project.milestones.map((item,i)=><button key={item.id} className={`${selected===i?'active':''} ${item.status==='Подтверждён'?'complete':''}`} onClick={()=>setSelected(i)}><span className="map-node">{statusIcon(item.status)}</span><span><small>Этап {i+1}</small><strong>{item.title}</strong><em>{item.status}</em></span>{item.xpAwarded&&<b>+100 XP</b>}</button>)}</nav><article className="milestone-content"><div className="milestone-title"><span className="stage-number">{String(selected+1).padStart(2,'0')}</span><div><span className={`proposal-status ${m.status.toLowerCase().replaceAll(' ','-')}`}>{m.status}</span><h2>{m.title}</h2><p>{m.objective}</p></div></div><section className="material"><div className="section-icon"><BookOpen/></div><div><span className="eyebrow violet">Короткий материал</span><p>{m.material}</p></div></section><section className="assignment"><span className="eyebrow">Практическое задание</span><h3>{m.assignment}</h3><label>Результат работы<textarea rows={7} value={m.result} disabled={role==='mentor'||m.status==='Подтверждён'} onChange={e=>updateMilestone(project.id,m.id,e.target.value)} placeholder="Опишите результат и добавьте ссылки на безопасные демонстрационные материалы"/></label>{role==='student'&&m.status!=='Подтверждён'&&<button className="btn" onClick={submit} disabled={m.status==='На проверке'}><Send size={17}/>{m.status==='На проверке'?'Отправлено на проверку':'Отправить наставнику'}</button>}</section>{m.feedback&&<section className="mentor-feedback"><ShieldCheck/><div><span>Обратная связь наставника</span><p>{m.feedback}</p>{m.review&&<small>{new Intl.DateTimeFormat('ru-RU',{dateStyle:'medium',timeZone:'Asia/Almaty'}).format(new Date(m.review.reviewedAt))} · {m.review.reviewer}</small>}</div></section>}{role==='mentor'&&m.status==='На проверке'&&<section className="review-box"><span className="eyebrow violet">Проверка наставника</span><h3>Проверьте результат, затем примите решение</h3><label>Комментарий<textarea rows={4} value={comment} onChange={e=>setComment(e.target.value)} placeholder="Что получилось и что стоит улучшить?"/></label><div><button className="btn ghost" onClick={()=>review('Нужна доработка')}><CircleAlert size={17}/>Вернуть на доработку</button><button className="btn learning" onClick={()=>review('Подтверждён')}><CheckCircle2 size={17}/>Подтвердить этап · +100 XP</button></div><small>Повторное подтверждение того же этапа не начисляет XP.</small></section>}{m.status==='Подтверждён'&&<div className="achievement"><Award/><div><strong>Навык подтверждён наставником</strong><p>Демонстрационное подтверждение внутри PRAKTIKA, не внешняя аккредитация.</p></div></div>}</article></div>
  </div>}
