'use client';
import {useState,type FormEvent} from 'react';
import {MonitorSmartphone,LogOut,KeyRound} from 'lucide-react';
import {useApp} from './provider';
import {Button} from './ui/button';
export function AccountSecurity(){
 const {data,refresh,notify}=useApp();const [username,setUsername]=useState(''),[password,setPassword]=useState(''),[confirmation,setConfirmation]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const me=data?.me;if(!me)return null;
 async function save(e:FormEvent){e.preventDefault();setBusy(true);setError('');try{const r=await fetch('/api/auth/credentials',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username,password,confirmPassword:confirmation})});const result=await r.json();if(!r.ok)throw new Error(result.error);setPassword('');setConfirmation('');await refresh();notify('Логин и пароль сохранены. Теперь можно войти на другом устройстве.');}catch(e){setError(e instanceof Error?e.message:'Ошибка сохранения');}finally{setBusy(false);}}
 async function logoutAll(){setBusy(true);setError('');try{const r=await fetch('/api/auth/logout-all',{method:'POST'});if(!r.ok)throw new Error('Не удалось завершить сессии');await refresh();notify('Вы вышли на всех устройствах.');}catch(e){setError(e instanceof Error?e.message:'Ошибка');}finally{setBusy(false);}}
 return <section className="panel security-panel"><div className="security-heading"><MonitorSmartphone size={24}/><div><h2>Один аккаунт. Все ваши устройства.</h2><p>{me.username?'Ваш логин: @'+me.username:'Завершите переход со старого аккаунта: задайте логин и пароль.'}</p></div></div>{!me.username?<form onSubmit={save}><label className="form-field">Новый логин<input required minLength={3} maxLength={24} pattern="[a-zA-Z][a-zA-Z0-9_]{2,23}" autoComplete="username" value={username} onChange={e=>setUsername(e.target.value)}/></label><label className="form-field">Новый пароль<input required type="password" minLength={12} maxLength={128} autoComplete="new-password" value={password} onChange={e=>setPassword(e.target.value)}/></label><label className="form-field">Повтор нового пароля<input required type="password" minLength={12} maxLength={128} autoComplete="new-password" value={confirmation} onChange={e=>setConfirmation(e.target.value)}/></label><Button type="submit" disabled={busy}><KeyRound size={16}/>Сохранить данные входа</Button></form>:<><p className="security-description">Откройте этот сайт на телефоне или другом компьютере и войдите с тем же логином и паролем. Проекты и профиль сохраняются в вашем аккаунте.</p><Button variant="outline" size="sm" disabled={busy} onClick={logoutAll}><LogOut size={15}/>Выйти на всех устройствах</Button></>}{error&&<div className="error-box" role="alert">{error}</div>}</section>;
}
