'use client';
import Link from 'next/link';
import {usePathname} from 'next/navigation';
import {BookOpen,LayoutGrid,BriefcaseBusiness,Users,ArrowUpRight,GraduationCap,Sparkles,ChevronRight,Plus,LogOut,UserRound} from 'lucide-react';
import {useApp} from './provider';
import {EffectsToggle} from './effects-toggle';
import {AuthDialog} from './auth-dialog';
import {Button} from './ui/button';
import type {ReactNode} from 'react';
export function Shell({children}:{children:ReactNode}){
 const path=usePathname();const {data,openAuth,logout,notify}=useApp(),me=data?.me;
 const links=[{href:'/catalog',icon:LayoutGrid,label:'Каталог задач'},{href:'/community',icon:Users,label:'Сообщество'},{href:'/team',icon:GraduationCap,label:'Моя практика'},{href:'/business',icon:BriefcaseBusiness,label:'Кабинет бизнеса'}];
 return <div className="app-shell"><aside className="sidebar"><Link className="brand" href="/catalog"><span className="brand-mark"><BookOpen size={24}/></span><span>Alem<span className="brand-sub">practice</span></span></Link><div className="workspace-label">УЧИСЬ. СОЗДАВАЙ. РАСТИ.</div><nav>{links.map(({href,icon:Icon,label})=><Link key={href} href={href} className={`nav-link ${path.startsWith(href)?'active':''}`}><Icon size={19}/>{label}{path.startsWith(href)&&<ChevronRight size={16}/>}</Link>)}</nav><Link href="/business/new" className="sidebar-create"><Plus size={18}/>Создать задачу</Link><div className="sidebar-note"><div className="note-icon"><GraduationCap size={24}/></div><strong>Большое начинается<br/>с первой практики.</strong><p>Соберите навыки в проект,<br/>а проект — в портфолио.</p><Link href="/guide">Как это работает <ArrowUpRight size={15}/></Link><span className="note-orbit" aria-hidden="true"/></div><div className="sidebar-footer"><span className="mini-logo">A</span><span>HackAlem 2026<small>Трек «Образование»</small></span><span className="online-dot"/></div></aside><div className="main-shell"><header className="topbar"><div className="breadcrumb">Пространство обучения <ChevronRight size={14}/><strong>{path==='/community'?'Сообщество':path==='/profile'?'Профиль':'Практика'}</strong></div><div className="topbar-controls"><EffectsToggle/><span className="ai-label"><Sparkles size={14}/>{data?.aiMode==='live'?'AI подключён':'AI demo'}</span>{me?<><Link href="/profile" className="user-chip"><span className="avatar">{me.name.slice(0,2).toUpperCase()}</span><span>{me.name}<small>{me.isTest?'Тестовый аккаунт':me.role==='student'?'Студент':'Бизнес'}</small></span></Link><button className="logout-button" aria-label="Выйти из аккаунта" onClick={()=>logout().catch(e=>notify(e.message))}><LogOut size={18}/></button></>:<><Button variant="ghost" onClick={()=>openAuth('login')}>Войти</Button><Button onClick={()=>openAuth()}><UserRound size={16}/>Начать практику</Button></>}</div></header><main><div className="route-enter" key={path}>{children}</div></main><footer className="page-footer">Alem Practice · превращаем знания в опыт<span>Учебные примеры отмечены в карточках</span></footer></div><AuthDialog/></div>
}
