'use client';
import Link from 'next/link';
import {usePathname} from 'next/navigation';
import {BookOpen,LayoutGrid,BriefcaseBusiness,Users,ArrowUpRight,GraduationCap,Sparkles,ChevronRight,Plus} from 'lucide-react';
import {useApp} from './provider';
import type {ReactNode} from 'react';
export function Shell({children}:{children:ReactNode}){
 const path=usePathname();const {data,role,actorId,setRole,setActorId}=useApp();
 const links=[{href:'/catalog',icon:LayoutGrid,label:'Каталог задач'},{href:'/team',icon:GraduationCap,label:'Моя практика'},{href:'/business',icon:BriefcaseBusiness,label:'Кабинет бизнеса'}];
 return <div className="app-shell"><aside className="sidebar"><Link className="brand" href="/catalog"><span className="brand-mark"><BookOpen size={24}/></span><span>Alem<span className="brand-sub">practice</span></span></Link><div className="workspace-label">ПРОСТРАНСТВО ПРАКТИКИ</div><nav>{links.map(({href,icon:Icon,label})=><Link key={href} href={href} className={`nav-link ${path.startsWith(href)?'active':''}`}><Icon size={19}/>{label}{path.startsWith(href)&&<ChevronRight size={16}/>}</Link>)}</nav><Link href="/business/new" className="sidebar-create"><Plus size={18}/>Создать задачу</Link><div className="sidebar-note"><div className="note-icon"><GraduationCap size={22}/></div><strong>Учитесь на деле</strong><p>Реальная задача сегодня.<br/>Опыт в портфолио завтра.</p><Link href="/guide">Как проходит практика <ArrowUpRight size={15}/></Link></div><div className="sidebar-footer"><span className="mini-logo">AI</span><span>AI Sana · HackAlem<small>Учебная демонстрация</small></span></div></aside><div className="main-shell"><header className="topbar"><div className="breadcrumb">Образование <ChevronRight size={14}/><strong>Практика</strong></div><div className="topbar-controls"><span className="ai-label"><Sparkles size={14}/> AI: {data?.aiMode==='live'?'подключён':'demo'}</span><div className="role-switch" aria-label="Демонстрационная роль"><button className={role==='student'?'selected':''} onClick={()=>setRole('student')}>Студент</button><button className={role==='business'?'selected':''} onClick={()=>setRole('business')}>Бизнес</button></div><label className="actor-select"><span className="sr-only">Демонстрационный профиль</span><select value={actorId} onChange={e=>setActorId(e.target.value)}>{(role==='business'?data?.businesses:data?.teams)?.map(x=><option value={x.id} key={x.id}>{x.name}</option>)}</select></label><span className="avatar">{role==='business'?<BriefcaseBusiness size={18}/>:<Users size={18}/>}</span></div></header><main>{children}</main><footer className="page-footer">Знания в реальных задачах<span>Демо · все организации и команды вымышлены</span></footer></div></div>
}
