'use client';
import {useState,type FormEvent} from 'react';
import Link from 'next/link';
import {ArrowLeft,ArrowRight,Send,GraduationCap,BookOpen,Users,Edit3,CheckCircle2,ExternalLink} from 'lucide-react';
import {useApp} from './provider';
import {Button} from './ui/button';
import {Dialog} from './ui/dialog';
import {ScoreBadge,TaskIcon} from './catalog';
import {ScorePanel} from './score-panel';
import {fieldKeys,labels,type TaskView} from '@/lib/domain';
import {plural} from '@/lib/utils';
export function TaskDetail({id}:{id:string}){
 const {data,role,actorId,setRole}=useApp();const [open,setOpen]=useState(false);
 if(!data)return <div className="loading">Загружаем задачу…</div>;const task=data.tasks.find(t=>t.id===id);if(!task)return <div className="page empty-state"><h2>Задача не найдена</h2><Link href="/catalog">Вернуться в каталог</Link></div>;
 return <div className="page"><Link href="/catalog" className="back-link"><ArrowLeft size={15}/>Каталог задач</Link><div className="detail-heading"><div className="task-icon"><TaskIcon topic={task.topic}/></div><div><div className="company-name">{task.ownerName} · {task.topic}</div><h1>{task.title}</h1></div><ScoreBadge task={task}/></div>{task.isDemo&&<div className="demo-notice">Учебный кейс: организация и данные вымышлены. Для демонстрации работы с заказчиком создайте задачу из аккаунта бизнеса.</div>}<div className="builder-grid"><div><div className="learning-card"><div className="panel-eyebrow"><GraduationCap size={18}/> ВАША ПРАКТИКА</div><h2>Знания, которые станут опытом</h2><div className="learning-columns"><div><h4>Чему научитесь</h4><div className="tags">{task.learning.skills.length?task.learning.skills.map(s=><span key={s}>{s}</span>):<p>Навыки пока не указаны</p>}</div></div><div><h4>Что нужно знать</h4><p>{task.learning.prerequisites.join(' · ')||'Обсудите с бизнесом'}</p></div></div><div className="learning-outcome"><BookOpen size={19}/><div><strong>Результат для портфолио</strong><p>{task.learning.portfolio||'Согласуйте ожидаемый результат с бизнесом'}</p></div></div></div><section className="panel task-fields"><div className="section-heading"><h2>О задаче</h2>{task.ownerId===actorId&&role==='business'&&<Button asChild variant="outline" size="sm"><Link href={`/business/edit/${id}`}><Edit3 size={14}/>Дополнить</Link></Button>}</div>{fieldKeys.map(k=><div key={k} className="detail-field"><h3>{labels[k]}{task.confirmedFields.includes(k)&&<CheckCircle2 size={13}/>}</h3><p className={!task.fields[k]?'missing-text':''}>{task.fields[k]||'Не указано — можно уточнить у бизнеса'}</p>{k==='data'&&task.fields.data?.match(/\/datasets\/[a-z-]+\.(?:csv|json)/)?.[0]&&<a className="dataset-link" href={task.fields.data.match(/\/datasets\/[a-z-]+\.(?:csv|json)/)![0]} download><ExternalLink size={14}/>Скачать учебные данные</a>}</div>)}</section></div><div className="sticky-column"><div className="panel apply-panel"><h3>Ваш следующий проект?</h3><p>Расскажите, как ваша команда видит решение. Бизнес ответит на предложение.</p><div className="apply-meta"><span><Users size={15}/>{task.proposalCount} {plural(task.proposalCount,['отклик','отклика','откликов'])}</span><span>{task.learning.difficulty}</span></div>{task.publicationStatus==='published'?(role==='student'?<Button onClick={()=>setOpen(true)}><Send size={16}/>Предложить решение</Button>:<Button variant="outline" onClick={()=>setRole('student')}>Войти как студент<ArrowRight size={15}/></Button>):<p className="notice">Задача ещё не опубликована.</p>}<small>Отклик доступен при любом рейтинге</small></div><ScorePanel fields={task.fields} confirmed={task.confirmedFields}/></div></div><ProposalDialog task={task} open={open} onOpenChange={setOpen}/></div>
}
function ProposalDialog({task,open,onOpenChange}:{task:TaskView;open:boolean;onOpenChange:(v:boolean)=>void}){
 const {run,notify,data,actorId}=useApp();const [idea,setIdea]=useState(''),[plan,setPlan]=useState(''),[days,setDays]=useState(14),[url,setUrl]=useState(''),[assumptions,setAssumptions]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError('');try{await run('createProposal',{taskId:task.id,idea,plan:plan.split('\n').map(x=>x.trim()).filter(Boolean),durationDays:days,prototypeUrl:url,assumptions});notify('Предложение отправлено. Следите за решением в «Моей практике».');onOpenChange(false);setIdea('');setPlan('');setUrl('')}catch(e){setError(e instanceof Error?e.message:'Не удалось отправить')}finally{setBusy(false)}}
 return <Dialog open={open} onOpenChange={onOpenChange} title="Предложите своё решение" description={`${data?.teams.find(t=>t.id===actorId)?.name} → ${task.ownerName}`}><form onSubmit={submit}><div className="dialog-task">{task.title}</div><label className="form-field">Идея решения<textarea value={idea} onChange={e=>setIdea(e.target.value)} required minLength={10} rows={3} placeholder="Как вы подойдёте к задаче?"/></label><label className="form-field">План работы<textarea value={plan} onChange={e=>setPlan(e.target.value)} required rows={3} placeholder="Каждый шаг с новой строки"/></label><div className="form-row"><label className="form-field">Срок, дней<input type="number" min={1} max={365} value={days} onChange={e=>setDays(Number(e.target.value))} required/></label><label className="form-field grow">Ссылка на прототип<input value={url} onChange={e=>setUrl(e.target.value)} required placeholder="https://…"/></label></div><button className="text-button" type="button" onClick={()=>setUrl('/demo/prototypes/sample')}><ExternalLink size={13}/>Использовать учебную ссылку</button><label className="form-field">Что нужно уточнить<input value={assumptions} onChange={e=>setAssumptions(e.target.value)} placeholder="Необязательно"/></label>{error&&<div className="error-box" role="alert">{error}</div>}<div className="form-actions"><Button type="button" variant="ghost" onClick={()=>onOpenChange(false)}>Отмена</Button><Button type="submit" disabled={busy}><Send size={15}/>{busy?'Отправляем…':'Отправить предложение'}</Button></div></form></Dialog>
}

